### ISSUE TITLE
Browse for CBSS by author should exclude editors unless there is no author

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#252]
Example: browsing by the letter "L" includes Michael Abdalla, Culinary Issues in Bar Ebraya’s Ethicon,” in _Symposium Syriacum VII: Uppsala University, Department of Asian and African Languages, 11–14 August 1996_, ed. René Lavenant, Orientalia Christiana Analecta 256 (Roma: Pontificio Istituto Orientale, 1998), 735–45. This is due to Lavenant being the editor of the volume.

It is likely the case that we only include editor elements if there is not an author element, but I need to figure out the best xpath that will capture what we want to capture, and exclude what we want to exclude

**Comment by wsalesky** [comment]
@wsalesky fixed in json, waiting until Tuesday to rerun data. New XPath uses only author tag if it exists, otherwise uses editor example: 
`<xsl:when test="$doc/descendant::tei:body/tei:bibl/tei:author[descendant::text() != ''] 
                        or $doc/descendant::tei:body/tei:biblStruct/descendant-or-self::tei:author[descendant::text() != '']">`

**Comment by wsalesky** [comment]
@wlpotter Need help checking this one

**Comment by wlpotter** [comment]
I think this is working so it only uses editors if there is no author. I think there might be a sorting issue still, but want to check at the meeting to make sure

**Comment by wlpotter** [comment]
Oh wait, nevermind, I see how it's sorting now. I keep forgetting that it still sorts within a letter bucket based on all of the authors (or editors if no authors), so multi-author items with a co-author whose name starts with 'A' will be listed first. All that to say, yes, I believe this is working correctly now
