### ISSUE TITLE
Record Page Rendering (Fonts, Whitespace, Text Format)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#3]
Some rendering is not as expected. See https://syriaca.org/person/1102

- [ ] person/note type=abstract is in grey not black and the size seems too big
- [ ] Labels for Sex and Death should be the same as Name and Event in size and plain (not bold)
- [ ] The event type="veneration" contains a desc instead of a p so it seems to be treated differently/incorrectly in rendering its footnote
- [ ] The handling of the whitespace from xml pretty-print seems to have pushed a period onto a line by itself at event xml:id="attestation1102-2 and this is pushing the footnote down, do we need to fix that in the TEI or can the app render that correctly?

**Comment by davidamichelson** [comment]
![NotesonRecord2022](https://user-images.githubusercontent.com/3083773/155175993-561b84e9-6c48-4c32-a985-6262677ac838.png)

**Comment by wlpotter** [comment]
Here are the XML lines for the tei:event with the extra newline before the footnote: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/saints/tei/1102.xml#L189-L191

Here are the lines for the two attestations that have a single whitespace before the footnote: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/saints/tei/1102.xml#L192-L199

**Comment by wsalesky** [comment]
Fixed all but the last. I think that is a TEI issue.

**Comment by davidamichelson** [comment]
@wlpotter Please make a batch change.

**Comment by davidamichelson** [comment]
White space still present before and after period at the end of attestations.

**Comment by wlpotter** [comment]
@wsalesky it may be the difference between how tei:desc and tei:p are being treated within tei:event.

Compare the two events: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/saints/tei/1102.xml#L189-L191 with https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/saints/tei/1102.xml#L192-L195
